<!DOCTYPE html>
<html lang="english">
  <head>
    <title>Animal Chip</title>
    <meta property="og:title" content="Animal Chip" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta property="twitter:card" content="summary_large_image" />

    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6,figure,blockquote,figcaption {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Inter;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.15;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }
    </style>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
      data-tag="font"
    />
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <div>
      <link href="./page2.css" rel="stylesheet" />

      <div class="page2-container">
        <div class="page2-frame">
          <div class="page2-group10">
            <div class="page2-frame1">
              <img
                alt="Search22"
                src="public/external/search22-saou-200h.png"
                class="page2-search"
              />
              <span class="page2-text"><span>Поиск животного</span></span>
              <img
                alt="pixelarticonssearch336"
                src="public/external/pixelarticonssearch336-how3.svg"
                class="page2-pixelarticonssearch"
              />
            </div>
            <div class="page2-frame2">
              <img
                alt="Rectangle324"
                src="public/external/rectangle324-qqfs-200h.png"
                class="page2-rectangle3"
              />
              <span class="page2-text02"><span>Регистрация</span></span>
              <img
                alt="pixelarticonscontactplus338"
                src="public/external/pixelarticonscontactplus338-21f.svg"
                class="page2-pixelarticonscontactplus"
              />
            </div>
            <a href="account" class="page2-navlink">
              <div class="page2-group2">
                <div class="page2-frame10">
                  <img
                    alt="Rectangle41635"
                    src="public/external/rectangle41635-3c7-200h.png"
                    class="page2-rectangle4"
                  />
                </div>
                <div class="page2-frame11">
                  <span class="page2-text04"><span>Войти</span></span>
                </div>
                <img
                  alt="pixelarticonslogin1636"
                  src="public/external/pixelarticonslogin1636-umjq.svg"
                  class="page2-pixelarticonslogin"
                />
              </div>
            </a>
            <a href="./" class="page2-navlink1">
              <div class="page2-frame3">
                <img
                  alt="Rectangle2114"
                  src="public/external/rectangle2114-tiu-200h.png"
                  class="page2-rectangle2"
                />
                <span class="page2-text06">
                  <span>
                    <span>Animal_chip</span>
                    <br />
                    <span></span>
                  </span>
                </span>
              </div>
            </a>
          </div>
          <div class="page2-frame14">
            <span class="page2-text11"><span>Все о чипировании</span></span>
          </div>
          <span class="page2-text13">
            <span>
              <span>
                Для идентификации кошек и собак лучший способ – чипирование. Он
                безопасен, характеризуется безболезненностью, используется
                больше 20 лет. В странах Европы чипирование давно стало нормой,
                как и другие процедуры – регулярный осмотр, вакцинация и др.
              </span>
              <br />
              <span>Преимущества чипирования</span>
              <br />
              <span>
                До момента начала использования чипирования опознавание животных
                проводили с помощью татуировок, клейма, бирок. Основными
                недостатками таких методов считают:
              </span>
              <br />
              <span>болезненность нанесения татуировки, клейма;</span>
              <br />
              <span>вероятность подделки указанных идентификаторов;</span>
              <br />
              <span>
                со временем клеймо, татуировка деформируются, бирки теряются.
              </span>
              <br />
              <span>
                С тех пор, как применяется чипирование, проблема идентификации
                решилась раз и навсегда.
              </span>
            </span>
          </span>
          <a href="./map" class="page2-navlink2">
            <div class="page2-frame4">
              <img
                alt="Rectangle10756"
                src="public/external/rectangle10756-5r4u.svg"
                class="page2-rectangle10"
              />
              <span class="page2-text28">
                <span>Где чипировать?</span>
                <br />
                <br />
              </span>
            </div>
          </a>
        </div>
      </div>
    </div>
  </body>
</html>
