<!DOCTYPE html>
<html lang="english">
  <head>
    <title>Page - exported project</title>
    <meta property="og:title" content="Page - exported project" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta property="twitter:card" content="summary_large_image" />

    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6,figure,blockquote,figcaption {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Inter;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.15;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }
    </style>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
      data-tag="font"
    />
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <div>
      <link href="./page.css" rel="stylesheet" />

      <div class="page-container">
        <div class="page-frame">
          <div class="page-group10">
            <div class="page-frame1">
              <img
                alt="Search22"
                src="public/external/search22-saou-200h.png"
                class="page-search"
              />
              <span class="page-text"><span>Поиск животного</span></span>
              <form action="/" method="get">
                  Поиск по типу животного: <input type="text" name="type"><br>
                  <input type="submit" value="Поиск"/>
              </form>
              <img
                alt="pixelarticonssearch336"
                src="public/external/pixelarticonssearch336-how3.svg"
                class="page-pixelarticonssearch"
              />
            </div>
            <div class="page-frame2">
              <img
                alt="Rectangle324"
                src="public/external/rectangle324-qqfs-200h.png"
                class="page-rectangle3"
              />
              <span class="page-text02"><span>Регистрация</span></span>
              <img
                alt="pixelarticonscontactplus338"
                src="public/external/pixelarticonscontactplus338-21f.svg"
                class="page-pixelarticonscontactplus"
              />
            </div>
            <a href="page3.html" class="page-navlink">
              <div class="page-group2">
                <div class="page-frame10">
                  <img
                    alt="Rectangle41635"
                    src="public/external/rectangle41635-3c7-200h.png"
                    class="page-rectangle4"
                  />
                </div>
                <div class="page-frame11">
                  <span class="page-text04"><span>Войти</span></span>
                </div>
                <img
                  alt="pixelarticonslogin1636"
                  src="public/external/pixelarticonslogin1636-umjq.svg"
                  class="page-pixelarticonslogin"
                />
              </div>
            </a>
            <a href="page.html" class="page-navlink1">
              <div class="page-frame3">
                <img
                  alt="Rectangle2114"
                  src="public/external/rectangle2114-tiu-200h.png"
                  class="page-rectangle2"
                />
                <span class="page-text06">
                  <span>
                    <span>Animal_chip</span>
                    <br />
                    <span></span>
                  </span>
                </span>
              </div>
            </a>
          </div>
          <a href="page2.html" class="page-navlink2">
            <div class="page-frame4">
              <img
                alt="Rectangle10756"
                src="public/external/rectangle10756-5r4u.svg"
                class="page-rectangle10"
              />
              <span class="page-text11"><span>Все о чипировании</span></span>
            </div>
          </a>
          <a href="index.html" class="page-navlink3">
            <div class="page-frame5">
              <img
                alt="Rectangle11757"
                src="https://aheioqhobo.cloudimg.io/v7/_playground-bucket-v2.teleporthq.io_/2617db15-d596-46a4-94ed-d505572f1092/d5fca2a8-20d4-4939-b099-65af477cd50f?org_if_sml=1813"
                class="page-rectangle11"
              />
              <span class="page-text13"><span>Где чипировать?</span></span>
            </div>
          </a>
          <span class="page-text15">
            <span>База данных чипированных животных</span>
          </span>
          <span class="page-text17">
            <span>
              Animal_chip - первая картографическая база данных чипированных
              собак, кошек и других животных в России и странах СНГ,
              объединенная с крупнейшей системой международного поиска
              EuroPetNet. В базе данных содержится информация о животных, где в
              качестве идентификации используются микрочипы и NFC-метки.
              Информация о вашем питомце будет доступна более чем в 40 странах
              по всему миру. Тем самым, давая, полную информацию для таможенной
              и ветеринарной службы, включая данные о вакцинациях в электронном
              виде.
            </span>
          </span>
        </div>
      </div>
    </div>
  </body>
</html>
