<!DOCTYPE html>
<html lang="english">
  <head>
    <title>Animal Chip</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta property="twitter:card" content="summary_large_image" />

    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6,figure,blockquote,figcaption {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Inter;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.15;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }
    </style>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
      data-tag="font"
    />
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <div>
      <link href="./page1.css" rel="stylesheet" />

      <div class="page1-container">
        <div class="page1-frame">
          <iframe
            src='https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d22070.34530287422!2d50.223068238008636!3d53.27191929841626!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1z0JLQtdGC0LXRgNC10L3QsNGA0L3QsNGPINC60LvQuNC90LjQutCw!5e1!3m2!1sru!2sru!4v1686159163644!5m2!1sru!2sru" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
            class="page1-iframe"
          ></iframe>
          <img
            alt="Rectangle11231"
            src="public/external/rectangle11231-puhu-200h.png"
            class="page1-rectangle1"
          />
          <a href="./account" class="page1-navlink">
            <div class="page1-group2">
              <div class="page1-frame10">
                <img
                  alt="Rectangle41635"
                  src="public/external/rectangle41635-3c7-200h.png"
                  class="page1-rectangle4"
                />
              </div>
              <div class="page1-frame11">
                <span class="page1-text"><span>Войти</span></span>
              </div>
              <img
                alt="pixelarticonslogin1636"
                src="public/external/pixelarticonslogin1636-umjq.svg"
                class="page1-pixelarticonslogin"
              />
            </div>
          </a>
          <a href="./" class="page1-navlink1">
            <div class="page1-group8">
              <img
                alt="Rectangle21231"
                src="public/external/rectangle21231-ejx9-200h.png"
                class="page1-rectangle2"
              />
              <span class="page1-text02">
                <span>
                  <span>Animal_chip</span>
                  <br />
                  <span></span>
                </span>
              </span>
            </div>
          </a>
          <div class="page1-group7">
            <img
              alt="Rectangle31232"
              src="public/external/rectangle31232-nhur-200h.png"
              class="page1-rectangle3"
            />
            <span class="page1-text07"><span>Регистрация</span></span>
            <img
              alt="pixelarticonscontactplus1234"
              src="public/external/pixelarticonscontactplus1234-1yew.svg"
              class="page1-pixelarticonscontactplus"
            />
          </div>
          <div class="page1-group9">
            <img
              alt="Search1232"
              src="public/external/search1232-bs1w-200h.png"
              class="page1-search"
            />
            <img
              alt="pixelarticonssearch1233"
              src="public/external/pixelarticonssearch1233-yk3k.svg"
              class="page1-pixelarticonssearch"
            />
            <span class="page1-text09"><span>Поиск животного</span></span>
          </div>
          <span class="page1-text11"><span>Где чипировать?</span></span>
          <a href="./about" class="page1-navlink2">
            <div class="page1-frame1">
              <img
                alt="Rectangle101233"
                src="public/external/rectangle101233-ao9.svg"
                class="page1-rectangle10"
              />
              <span class="page1-text13"><span>Все о чипировании</span></span>
            </div>
          </a>
        </div>
      </div>
    </div>
  </body>
</html>
